product:
    agentCoreContainerName: "agent-core-test"
    alertManagerPodPrefix: "alertmanager"
    controlPlaneAgent: "mayastor-agent-core"
    controlPlaneCoreAgent: "mayastor-agent-core"
    controlPlaneCsiController: "mayastor-csi-controller"
    controlPlaneEtcd: "mayastor-etcd"
    controlPlanePoolOperator: "mayastor-operator-diskpool"
    controlPlaneRestServer: "mayastor-api-rest"
    controlPlaneLocalpvProvisioner: "mayastor-localpv-provisioner"
    controlPlaneObsCallhome: "mayastor-obs-callhome"
    cpuCount: "2"
    crdGroupName: "openebs.io"
    crdPoolsResourceName: "diskpools"
    csiDaemonsetName: "mayastor-csi-node"
    csiNodeServiceAppLabel: "csi-node"
    csiNodeServiceDaemonset: "mayastor-csi-node"
    csiNodeContainerName: "csi-node"
    csiProvisioner: "io.openebs.csi-mayastor"
    daemonsetName: "mayastor-io-engine"
    dataPlaneNats: "nats"
    dockerOrganisation: "openebs"
    engineLabel: "openebs.io/engine"
    engineLabelValue: "mayastor"
    etcdYaml: "etcd"
    eventBusNatsSts: "mayastor-nats"
    haNodeAgentDs: "mayastor-agent-ha-node"
    haNodeAgentPodPrefix: "mayastor-agent-ha-node"
    helmReleaseName: "mayastor"
    ioEnginePodLabelValue: "io-engine"
    ioEnginePodName: "mayastor-io-engine"
    jaegersCrdName: "jaegers.jaegertracing.io"
    kubectlPluginName: "kubectl-mayastor"
    kubectlPluginPort: 30011
    logConfigResources:
      - "mayastor-etcd"
      - "mayastor-loki"
      - "mayastor-promtail"
      - "mayastor-io-engine"
      - "mayastor-agent-core"
      - "mayastor-agent-ha-node"
      - "mayastor-csi-controller"
      - "mayastor-csi-node"
      - "mayastor-operator-diskpool"
      - "mayastor-api-rest"
      - "mayastor-localpv-provisioner"
      - "mayastor-obs-callhome"
    logDumpCsiAttacherName: "csi-attacher"
    logDumpCsiDriverRegistrarName: "csi-driver-registrar"
    logDumpCsiProvisionerName: "csi-provisioner"
    logDumpCsiResizerName: "csi-resizer"
    logDumpCsiSnapshotControllerName: "csi-snapshot-controller"
    logDumpCsiSnapshotterName: "csi-snapshotter"
    logDumpDirs:
      - "agent-core"
      - "csi-controller"
      - "operator-diskpool"
      - "api-rest"
    logDumpEngineLabel: "io-engine"
    logDumpHaClusterName: "agent-ha-cluster"
    logDumpMetricsExporterLabel: "metrics-exporter"
    loggingLabel: "openebs.io/logging"
    logLevel: "debug"
    lokiStatefulset: "mayastor-loki"
    metricsPollingInterval: "30s"
    mongoAuthDatabase: "test"
    mongoAuthPassword: "admin123"
    mongoAuthRootPassword: "r00tAdmin"
    mongoAuthUsername: "admin"
    mongoDatabasePort: 27017
    mongoDefaultChartVersion: "14.5.0"
    mongoHelmRepo: "bitnami/mongodb"
    mongoHelmRepoName: "bitnami"
    mongoHelmRepoUrl: "https://charts.bitnami.com/bitnami"
    mongoReleaseName: "ms-mongo"
    natsPort: "4222"
    nvmeControllerModel: "Mayastor NVMe controller"
    partialRebuildCpTimeout: "240s"
    podLabelKey: "app"
    poolCrdName: "diskpools.openebs.io"
    productName: "mayastor"
    productNamespace: "mayastor"
    prometheusPodPrefix: "prometheus"
    prometheusPort: 30090
    promtailDaemonsetName: "mayastor-promtail"
    restApiPort: 8081
    restApiService: "mayastor-api-rest"
    statsConfigMapName: "mayastor-event-store"
    statsDeployment: "mayastor-obs-callhome"
    statsPort: "9090"
    statsService: "mayastor-obs-callhome-stats"
    upgradePodLabelValue: "upgrade"
    diskPoolAPIVersionMap:
      develop: "openebs.io/v1beta2"
      2.0.0: "openebs.io/v1alpha1"
      2.0.1: "openebs.io/v1alpha1"
      2.1.0: "openebs.io/v1alpha1"
      2.2.0: "openebs.io/v1alpha1"
      2.3.0: "openebs.io/v1alpha1"
      2.4.0: "openebs.io/v1beta1"
      2.5.0: "openebs.io/v1beta1"
      2.6.0: "openebs.io/v1beta2"
    chartName: "mayastor/mayastor"
    chartVersion: "0.0.0-main"
    localPVContainerName: "mayastor-localpv-provisioner"
